<a href="https://colab.research.google.com/github/kobebryantandlebron/Linear-Algebra-58019/blob/main/Practical_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PROBLEM NUMBER 1

In [3]:
import numpy as np

A = np.array ([[1,2,3],[4,5,6]])
B = np.array ([[1,2],[3,4],[5,6]])
C = np.array ([[1,2,3],[4,5,6],[7,8,9]])
D = np.array ([[1,2],[3,4]])
print(A) 
print(B)
print(C)
print(D)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [3 4]]


In [6]:
dot = np.dot(A,B)
print   (dot)

[[22 28]
 [49 64]]


In [4]:
sum = D + D
print(sum)


[[2 4]
 [6 8]]


In [5]:
prod = C * 2
print(prod)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


PROBLEM NUMBER 2

In [7]:
import numpy as np
A = np.array ([5,3,-1])

print(A.size)

print(type(A))

print(A.shape)

print(A.ndim)

3
<class 'numpy.ndarray'>
(3,)
1
