<a href="https://colab.research.google.com/github/kobebryantandlebron/Linear-Algebra-58019/blob/main/Python_exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Representing Vectors

In [2]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])
print ('Vector A is' , A)
print ('Vector B is' , B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [3]:
U = np.array ([[1,2,3],[4,5,6]])
U

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
U = np.array ([[1,2,3],[4,5,6]])
U
U.size

6

Space

Vector space are mathematical objects that abstractly capture the geometry and algebra of linear equations


Addition of Vectors

In [5]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [6]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
resultant

array([1, 1, 0])

Subtraction of Vectors

In [7]:
diff = addend1 - addend2
diff

array([-1, -1,  0])

In [8]:
diff2 = np.subtract(addend1,addend2)
diff2

array([-1, -1,  0])

Multiplication of Vectors

In [9]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

In [10]:
A = np.array([2,3])
B = np.array([1,7])
cross = np.cross(A,B)
print(cross)

11


In [11]:
A = np.array([2,3,4])
B = np.array([1,7,1])
cross = np.cross(A,B)
print(cross)

[-25   2  11]


In [12]:
import numpy as np
A = np.array ([2,3])
B = np.array ([1,7])
res = np.dot(A,B)
res

23