<a href="https://colab.research.google.com/github/kobebryantandlebron/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. sum = A + B
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
sum = A + B
print(sum)

[[ 1 -3]
 [ 6  4]]


In [3]:
# 2. difference1 = B - A
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
difference1 = B - A
print(difference1)

[[11 -3]
 [-2  2]]


In [4]:
# 3. difference2 = A - B 
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
difference2 = A - B
print(difference2)


[[-11   3]
 [  2  -2]]
